# Generated by Django 2.2.12 on 2020-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
