# Generated by Django 2.2.12 on 2020-05-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMonitor', '0002_auto_20200506_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinfothreshold',
            name='file_transfer_speed_threshold',
        ),
        migrations.AddField(
            model_name='serverinfothreshold',
            name='ping_threshold',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='serverinfothreshold',
            name='tcp_received_Mbps_threshold',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='serverinfothreshold',
            name='tcp_sent_Mbps_threshold',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='HTML_open_time_threshold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='backend_management_system_open_time_threshold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='bandwidth_threshold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='cpu_threshold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='disk_threshold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='memory_threshold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serverinfothreshold',
            name='microservices_exec_time_threshold',
            field=models.FloatField(),
        ),
    ]
