# Generated by Django 2.2.12 on 2020-05-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMonitor', '0003_auto_20200512_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildServerList',
            fields=[
                ('server_ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
